controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

site.logout:
    path:
        en: /logout
        fr: /deconnexion
    methods: GET
